# Generated by Django 4.0.7 on 2022-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='channel',
            field=models.CharField(choices=[('PHONE_NUMBER', 'PHONE_NUMBER'), ('EMAIL', 'EMAIL'), ('ALL', 'ALL')], default='ALL', max_length=30),
        ),
    ]
